# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Mobile Challenge' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Mobile Challenge
  pod 'SkyFloatingLabelTextField', '~> 3.0'

  target 'Mobile ChallengeTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
